CREATE TABLE [dbo].[ArcTodoItems]
(
    [ItemKey]  UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	[ArcKey]   UNIQUEIDENTIFIER NOT NULL,
	[DateLogged] DATETIME NOT NULL,
	[Text] NVARCHAR(50)
    PRIMARY KEY CLUSTERED ([ItemKey] ASC)
)
