CREATE TABLE [dbo].[Characters] (
    [CharacterKey]  UNIQUEIDENTIFIER NOT NULL,
    [FirstName]     NVARCHAR (50)    NULL,
    [LastName]      NVARCHAR (50)    NULL,
    [Portrait]   NVARCHAR (250)   NULL,
    [RaceKey]       UNIQUEIDENTIFIER NOT NULL,
    [ClassKey]      UNIQUEIDENTIFIER NOT NULL,
    [BackgroundKey] UNIQUEIDENTIFIER NOT NULL,
	[Fears]			NVARCHAR (250)   NULL,
	[Ideals]		NVARCHAR (250)   NULL,
    [Backstory]     NVARCHAR (MAX)   NULL,
    [Languages] NVARCHAR(250) NULL, 
    [Alignment] NVARCHAR(2) NOT NULL DEFAULT 'TN', 
    [Level] INT NOT NULL DEFAULT 1, 
    [MaxHP] INT NOT NULL DEFAULT 1, 
	[Proficiency] INT NOT NULL DEFAULT 2,
    [Strength] INT NOT NULL DEFAULT 10, 
    [Dexterity] INT NOT NULL DEFAULT 10, 
    [Constitution] INT NOT NULL DEFAULT 10, 
    [Intelligence] INT NOT NULL DEFAULT 10, 
    [Wisdom] INT NOT NULL DEFAULT 10, 
    [Charisma] INT NOT NULL DEFAULT 10, 
    [Abilities] NVARCHAR(MAX) NULL, 
    [Status] NVARCHAR(MAX) NULL,
    [Armor] NVARCHAR(25) NULL, 
    [ArmorClass] INT NOT NULL DEFAULT 10, 
    [SpellcastingAbility] NVARCHAR(10) NULL , 
    [SpellcastingMod] INT NOT NULL DEFAULT 1, 
    [SpellSaveDC] INT NOT NULL DEFAULT 10, 
    [SpellsPerDay] INT NOT NULL DEFAULT 0, 
    [Cantrips] INT NOT NULL DEFAULT 0, 
    [Level1Spells] INT NOT NULL DEFAULT 0, 
    [Level2Spells] INT NOT NULL DEFAULT 0, 
    [Level3Spells] INT NOT NULL DEFAULT 0, 
    [Level4Spells] INT NOT NULL DEFAULT 0, 
    [Level5Spells] INT NOT NULL DEFAULT 0, 
    [Level6Spells] INT NOT NULL DEFAULT 0, 
    [Level7Spells] INT NOT NULL DEFAULT 0, 
    [Level8Spells] INT NOT NULL DEFAULT 0, 
    [Level9Spells] INT NOT NULL DEFAULT 0, 
    [Copper] INT NOT NULL DEFAULT 0, 
    [Silver] INT NOT NULL DEFAULT 0, 
    [Electrum] INT NOT NULL DEFAULT 0, 
    [Gold] INT NOT NULL DEFAULT 0, 
    [Platinum] INT NOT NULL DEFAULT 0, 
    [Inventory] NVARCHAR(MAX) NULL, 
    [LastUpdateDate] DATETIME NOT NULL DEFAULT GETDATE(), 
    PRIMARY KEY CLUSTERED ([CharacterKey] ASC)
);

