CREATE TABLE [dbo].[DungeonTileTraps]
(
	[TrapKey] UNIQUEIDENTIFIER NOT NULL,
	[TileKey] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	[Description] NVARCHAR(MAX) NULL,
	[NatureKey] UNIQUEIDENTIFIER NOT NULL,
	[TypeKey] UNIQUEIDENTIFIER NOT NULL,
	[SaveDC] INT NULL,
	[AttackBonus] INT NULL,
	[Damage] NVARCHAR(10) NULL,
    PRIMARY KEY CLUSTERED ([TrapKey] ASC)
)
