CREATE TABLE [dbo].[MagicItems]
(
	[ItemKey] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	[Type] UNIQUEIDENTIFIER NOT NULL,
	[Rarity] UNIQUEIDENTIFIER NOT NULL,
	[HasAttunement] BIT NOT NULL DEFAULT 0,
	[Description] NVARCHAR(MAX) NULL,
    PRIMARY KEY CLUSTERED ([ItemKey] ASC)
)
