CREATE TABLE [dbo].[Players]
(
	[PlayerKey] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [Level] INT NOT NULL DEFAULT 1, 
    [MaxHP] INT NOT NULL DEFAULT 1, 
    [Strength] INT NOT NULL DEFAULT 10, 
    [Dexterity] INT NOT NULL DEFAULT 10, 
    [Constitution] INT NOT NULL DEFAULT 10, 
    [Intelligence] INT NOT NULL DEFAULT 10, 
    [Wisdom] INT NOT NULL DEFAULT 10, 
    [Charisma] INT NOT NULL DEFAULT 10, 
    [Abilities] NVARCHAR(MAX) NULL, 
    [Status] NVARCHAR(MAX) NULL
)
