CREATE TABLE [dbo].[Traps]
(
	[TrapKey] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	[Nature] UNIQUEIDENTIFIER NOT NULL,
	[Type] UNIQUEIDENTIFIER NOT NULL,
	[Description] NVARCHAR(MAX),
    PRIMARY KEY CLUSTERED ([TrapKey] ASC)
)
