CREATE TABLE [dbo].[TrapTypes]
(
	[TypeKey] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	[SaveDC] NVARCHAR(10) NOT NULL,
	[AttackBonus] NVARCHAR(10) NOT NULL,
    PRIMARY KEY CLUSTERED ([TypeKey] ASC)
)
